feat: Implement required traits for `ChunkType`
iandrc/pngme pull request #2
Opened 2022-07-24 19:23 UTC by iandrc

2022-07-24 19:49 UTC, Mart-Bogdan reviewed
Some minor comments for code.

2022-07-24 19:49 UTC, Mart-Bogdan commented on src/chunk_type.rs
> +        if value.len() != 4 {
This check is meaningless, as we are using array here, not slice. 

Arrays have fixed length.

2022-07-24 19:49 UTC, Mart-Bogdan commented on src/chunk_type.rs
> +        if s.len() != 4 {
for example, her it is ok

2022-07-24 19:49 UTC, Mart-Bogdan commented on src/chunk_type.rs
> +            for (index, c) in "RuSt".chars().enumerate() {
If we work with utf-8 strings beyound ASCII charset, then most chars would be > 256. Actually in rust char is u32.

I'd suggest just get u8's from string and encode them directly.

Also s.len() is not checking chars, but bytes in Rust.

2022-07-24 19:52 UTC, iandrc commented on src/chunk_type.rs
> +        if value.len() != 4 {
Does it mean Rust will guarantee that the incoming param will always have the length of 4?

2022-07-24 19:54 UTC, Mart-Bogdan commented on src/chunk_type.rs
> +        if value.len() != 4 {
yes. It's statically checked,

But it won't guarantee that all indexes are filled with meaningful data.

That's up to caller.

2022-07-24 20:00 UTC, iandrc commented on src/chunk_type.rs
> +            for (index, c) in "RuSt".chars().enumerate() {
Sorry, I didn't get the second part. What do you mean by saying `"encode them directly"`?

Thanks, I'll try to memorize it :)

2022-07-24 20:34 UTC, Mart-Bogdan commented on src/chunk_type.rs
> +            for (index, c) in "RuSt".chars().enumerate() {
I mean jsut store u8's. Not funn chars. Then, hhen you extract text from PNG you could jsut put back taht u8's and assemble string.

2022-07-25 06:41 UTC, TheBestTvarynka requested changes
It's good but I have a few comments

2022-07-25 06:41 UTC, TheBestTvarynka commented on src/chunk_type.rs
> +            }
make it simpler:
```rust
bytes[0..4].copy_from_slice(s.as_bytes());
```

2022-07-25 06:41 UTC, TheBestTvarynka commented on src/chunk_type.rs
> +            Ok(ChunkType { bytes: value })
Your `TryFrom` and `FromStr` implementations are not complete. You are not checking for the actual chunk type value. We have a concrete list of allowed chunk types in the PNG format. For example, chunk type "code" does not exist. You should handle check such situations

2022-07-25 06:41 UTC, TheBestTvarynka commented on src/chunk_type.rs
> +        let expected = [82, 117, 83, 116];
Please, use valid chunk types in your tests

2022-07-25 06:46 UTC, TheBestTvarynka commented on src/chunk_type.rs
> +        let expected = [82, 117, 83, 116];
Also, you may add readable chunk type value in the comment above of the array. Example:
```rust
// IHDR
let expected = [73, 72, 68, 82];
```

2022-07-25 18:48 UTC, iandrc commented on src/chunk_type.rs
> +        let expected = [82, 117, 83, 116];
Thanks for the comment, yet it's the unit tests provided by the course designer :)

2022-07-25 18:53 UTC, iandrc commented on src/chunk_type.rs
> +            }
Wow, thanks. Looks much better

2022-07-25 18:55 UTC, iandrc commented on src/chunk_type.rs
> +            for (index, c) in "RuSt".chars().enumerate() {
Refactored with @TheBestTvarynka 's suggestion :)

2022-07-25 19:12 UTC, iandrc commented on src/chunk_type.rs
> +            Ok(ChunkType { bytes: value })
It's planned for the following PR :)

2022-07-25 19:12 UTC, merged